### ISSUE TITLE
provide raw data on zenodo as well

### ISSUE THREAD

**Issue by florian-huber** [florian-huber/weather_prediction_dataset#1]

**Comment by colinsauze** [comment]
Is the Zenodo URL in the README (https://zenodo.org/record/477093) supposed to work? I am getting a page not found error when accessing it.

**Comment by florian-huber** [comment]
Thanks!
I corrected the url (https://doi.org/10.5281/zenodo.4770937).

**Comment by florian-huber** [comment]
Raw data from ECA&D which was used to create the dataset is now on zenodo as well: https://doi.org/10.5281/zenodo.4964287
