### ISSUE TITLE
Add missing references

### ISSUE THREAD

**Issue by florian-huber** [florian-huber/weather_prediction_dataset#10]
Currently there is still a bunch of references missing.... (e.g. sci-kit learn etc.)

**Comment by psteinb** [comment]
I am happy to help with this. I only started my pass of the paper. I already fixed some very German sounding formulations.

**Comment by florian-huber** [comment]
Those German sounding formulations must have been introduced by someone else ... :stuck_out_tongue_winking_eye:

**Comment by psteinb** [comment]
I hope I didn't miss any.
