### ISSUE TITLE
Use ML model (random forest?) to predict the month

### ISSUE THREAD

**Issue by florian-huber** [florian-huber/weather_prediction_dataset#6]
To show that the dataset can be used with both ML and DL, it would be nice to have a notebook (and as output a figure) on a classical ML model that predicts the months from the weather data of a single day. For instance a random forest?

**Comment by psteinb** [comment]
Let me look into this.

**Comment by florian-huber** [comment]
Hi @psteinb , I think @dafnevk has something nearly ready for this one?

**Comment by psteinb** [comment]
I wasn't aware of this. Sorry. Please let me know what more can be done.

**Comment by florian-huber** [comment]
A notebook for this was added in #7 and I just also added the confusion matrix as a figure to the manuscript.
