### ISSUE TITLE
Add binary classification column

### ISSUE THREAD

**Issue by dafnevk** [florian-huber/weather_prediction_dataset#8]
It would be nice if it's also possible to show binary classification with this dataset. Add a column to the dataset, e.g. 'BBQ weather' (that is based on the other columns of the dataset).

**Comment by colinsauze** [comment]
I like that idea, you could even add some homework to check how good you prediction was in the real world by looking at the weather observations a day later.

**Comment by florian-huber** [comment]
I also like the idea a lot (thanks Berend) and I added this to the dataset creation notebook.

Still have to upload the labels to zenodo. I think I would not add the `BBQ_weather` columns to actual data but rather provide a separate bbq_labels csv file. What do you think @colinsauze @dafnevk?

**Comment by psteinb** [comment]
If you choose to keep a common set of columns that could serve as key for a join, I think a separate csv is doable.

**Comment by florian-huber** [comment]
Good point Peter. Right now I kept the `DATE` column in both, so they could easily be joined.

**Comment by florian-huber** [comment]
Here's now a notebook on the BBQ weather prediction: https://github.com/florian-huber/weather_prediction_dataset/blob/main/notebooks/machine_learning_classification_bbq.ipynb (random forest)

**Comment by colinsauze** [comment]
I just tried to run your notebook and it fails because weather_prediction_bbq_labels.csv isn't in the dataset directory, was it supposed to be or do you expect people to generate it by running the Create_weather_predicition_dataset notebook? That is also failing for me because I can't get the data from Zenodo right now.

**Comment by florian-huber** [comment]
Hi Colin, I forgot to push the labels. Did it now, so they are in `/dataset/`.

I made an issue to not forget to in the end upload all data and labels (and to check the link) --> #11

**Comment by colinsauze** [comment]
I just tried again and the BBQ weather prediction notebook runs now.

**Comment by florian-huber** [comment]
BBQ_weather labels are now also on zenodo: https://doi.org/10.5281/zenodo.4980359
To me this would close this issue.
